dev *options:
  node_modules/.bin/esbuild \
    form.tsx \
    --bundle \
    --minify \
    --format=esm \
    --alias:react=preact/compat \
    --jsx-factory=h \
    --jsx-fragment=Fragment \
    --outfile=../datasette_jsonschema_forms/static/form.min.js \
    {{options}}
